import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Header from '../src/component/Header'
import Navbar from '../src/component/Navbar'
import Work from './Work'
import Projects from './Projects'
import Other from './Other'

export default function Home( { posts }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Xavier Nishikawa</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header/>
        <Navbar/>
        <Work/>
        <Projects props={posts}/>
        <Other/>

      </main>

      
    </div>
  )
}

export const getStaticProps = async () => {
  const posts = await fetch("https://berowra.xavier.deta.app/api/collection/t7tp38g89mkw?content").then(r => r.json());
  return {
    props: {
      //pp: 'Next.js is making me cry'
      posts
    },
    revalidate: 10
  }
}
