import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Header from '../component/Header'
import Work from './Work'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Xavier Nishikawa</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header/>
        <Work/>

      </main>

      
    </div>
  )
}
